# Generated by Django 4.2.8 on 2026-04-08 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cpu', 'Procesador (CPU)'), ('ram', 'Memoria RAM'), ('disco', 'Disco Duro / SSD'), ('gpu', 'Tarjeta Gráfica (GPU)'), ('motherboard', 'Placa Base'), ('fuente', 'Fuente de Poder'), ('tarjeta_red', 'Tarjeta de Red'), ('optico', 'Unidad Óptica (CD/DVD)'), ('case', 'Gabinete / Case'), ('monitor', 'Monitor'), ('teclado', 'Teclado'), ('mouse', 'Mouse'), ('impresora', 'Impresora'), ('ups', 'UPS / Regulador'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=200, verbose_name='Modelo')),
                ('especificaciones', models.TextField(blank=True, help_text='Ej: Intel Core i5-10400, 2.9GHz, 6 núcleos', verbose_name='Especificaciones técnicas')),
                ('numero_serie', models.CharField(blank=True, max_length=200, verbose_name='Número de serie')),
                ('capacidad', models.CharField(blank=True, help_text='Ej: 8GB, 500GB, 256GB SSD', max_length=100, verbose_name='Capacidad')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En mantenimiento'), ('dado_baja', 'Dado de baja')], default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Dirección de Informática, Recursos Humanos, etc.', max_length=100, unique=True, verbose_name='Nombre del departamento')),
                ('codigo', models.CharField(help_text='Ej: DI, RRHH, etc.', max_length=10, unique=True, verbose_name='Código abreviado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(help_text='Ej: PC-001, LAP-DIR-003, etc.', max_length=100, unique=True, verbose_name='Identificación del equipo')),
                ('tipo_equipo', models.CharField(default='Desktop', help_text='Ej: Desktop, Laptop, Servidor, Impresora', max_length=50, verbose_name='Tipo de equipo')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=150, verbose_name='Modelo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En mantenimiento'), ('dado_baja', 'Dado de baja')], default='activo', max_length=20)),
                ('ubicacion', models.CharField(help_text='Ej: Oficina 201, Despacho del Director, Sala de servidores', max_length=200, verbose_name='Ubicación física')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('mac', models.CharField(blank=True, help_text='Formato: AA:BB:CC:DD:EE:FF', max_length=17, verbose_name='Dirección MAC')),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, verbose_name='Sistema operativo')),
                ('numero_inventario', models.CharField(blank=True, max_length=100, verbose_name='Número de inventario físico')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable del equipo')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departamento')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['identificacion'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('cargo', models.CharField(help_text='Ej: Especialista en Redes, Director, etc.', max_length=150, verbose_name='Cargo')),
                ('rol', models.CharField(choices=[('root', 'Super Administrador (Root)'), ('admin_red', 'Administrador de Red'), ('seguridad', 'Responsable de Seguridad Informática'), ('usuario', 'Usuario Normal')], default='usuario', max_length=20, verbose_name='Rol en el sistema')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departamento', verbose_name='Departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
                'permissions': [('puede_gestionar_usuarios', 'Puede gestionar usuarios del sistema'), ('puede_gestionar_inventario', 'Puede gestionar inventario de equipos'), ('puede_ver_admin', 'Puede ver paneles administrativos')],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cambio_hardware', 'Cambio de Hardware Detectado'), ('nuevo_usuario', 'Nuevo Usuario Registrado'), ('nuevo_documento', 'Nuevo Documento Subido'), ('alerta_seguridad', 'Alerta de Seguridad'), ('sistema', 'Notificación del Sistema'), ('inventario', 'Actualización de Inventario')], max_length=30)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje detallado')),
                ('leida', models.BooleanField(default=False)),
                ('enlace', models.CharField(blank=True, help_text='URL a la que redirige al hacer clic en la notificación', max_length=200, verbose_name='Enlace relacionado')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(default='general', help_text='general para chat de todos, privado_X_Y para privado', max_length=100, verbose_name='Canal del mensaje')),
                ('contenido', models.TextField(verbose_name='Contenido del mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de chat',
                'verbose_name_plural': 'Mensajes de chat',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creado', 'Componente creado'), ('modificado', 'Componente modificado'), ('eliminado', 'Componente eliminado'), ('cambio_detectado', 'Cambio no autorizado detectado')], max_length=25, verbose_name='Tipo de acción')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Estado anterior del componente')),
                ('valor_nuevo', models.TextField(blank=True, verbose_name='Nuevo estado del componente')),
                ('campos_cambiados', models.TextField(blank=True, verbose_name='Lista de campos que cambiaron')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.componente', verbose_name='Componente afectado')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipo', verbose_name='Equipo afectado')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Historial de componente',
                'verbose_name_plural': 'Historiales de componentes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Documento a compartir en la red interna', upload_to='documentos/%Y/%m/', verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre original del archivo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del documento')),
                ('visible_todos', models.BooleanField(default=True, help_text='Si está activo, todos los usuarios pueden descargarlo', verbose_name='Visible para todos')),
                ('tamano', models.PositiveBigIntegerField(default=0, verbose_name='Tamaño en bytes')),
                ('tipo_mime', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descargas', models.PositiveIntegerField(default=0)),
                ('departamentos_visibles', models.ManyToManyField(blank=True, help_text='Dejar vacío si es visible para todos', to='core.departamento', verbose_name='Departamentos con acceso')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddField(
            model_name='componente',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='core.equipo', verbose_name='Equipo al que pertenece'),
        ),
    ]
