# Generated by Django 4.2.8 on 2026-04-08 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='activado_2fa',
            field=models.BooleanField(default=False, verbose_name='Autenticación de dos factores activa'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta (por intentos fallidos)'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='dias_expiracion_password',
            field=models.PositiveIntegerField(default=90, help_text='Días después de los cuales se obliga a cambiar (0=sin expiración)', verbose_name='Días para expiración de contraseña'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_ultimo_cambio_password',
            field=models.DateTimeField(blank=True, help_text='Se actualiza automáticamente al cambiar la contraseña', null=True, verbose_name='Fecha del último cambio de contraseña'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='intentos_fallidos_login',
            field=models.PositiveIntegerField(default=0, verbose_name='Intentos fallidos de login consecutivos'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='secret_2fa',
            field=models.CharField(blank=True, help_text='Generada automáticamente al activar 2FA', max_length=100, verbose_name='Clave secreta TOTP (2FA)'),
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de inicio')),
                ('direccion_ip', models.CharField(default='0.0.0.0', max_length=45, verbose_name='Dirección IP')),
                ('navegador', models.CharField(default='Otro', max_length=50, verbose_name='Navegador')),
                ('sistema_operativo', models.CharField(default='Otro', max_length=30, verbose_name='Sistema operativo')),
                ('dispositivo', models.CharField(default='Desktop', max_length=20, verbose_name='Tipo de dispositivo')),
                ('exitosa', models.BooleanField(default=True, verbose_name='Login exitoso')),
                ('cierre_sesion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de cierre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de sesión',
                'verbose_name_plural': 'Registros de sesiones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('login_fallido', 'Intento de login fallido'), ('logout', 'Cierre de sesión'), ('registro_usuario', 'Registro de usuario'), ('cambio_rol', 'Cambio de rol'), ('activar_usuario', 'Activar usuario'), ('desactivar_usuario', 'Desactivar usuario'), ('eliminar_usuario', 'Eliminación de usuario'), ('cambiar_password', 'Cambio de contraseña'), ('password_expirada', 'Contraseña expirada'), ('cuenta_bloqueada', 'Cuenta bloqueada por intentos fallidos'), ('subir_documento', 'Subida de documento'), ('eliminar_documento', 'Eliminación de documento'), ('equipo_creado', 'Equipo registrado'), ('equipo_modificado', 'Equipo modificado'), ('equipo_eliminado', 'Equipo eliminado'), ('componente_creado', 'Componente agregado'), ('componente_modificado', 'Componente modificado'), ('componente_eliminado', 'Componente eliminado'), ('2fa_activada', '2FA activada'), ('2fa_desactivada', '2FA desactivada'), ('otro', 'Otra acción')], max_length=30, verbose_name='Tipo de acción')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo afectado')),
                ('objeto_id', models.CharField(blank=True, max_length=100, verbose_name='ID del objeto')),
                ('descripcion', models.TextField(verbose_name='Descripción de la acción')),
                ('direccion_ip', models.CharField(default='0.0.0.0', max_length=45, verbose_name='Dirección IP')),
                ('datos_anterior', models.TextField(blank=True, help_text='Valores del objeto antes de la modificación', null=True, verbose_name='Estado anterior (JSON)')),
                ('datos_nuevo', models.TextField(blank=True, help_text='Valores del objeto después de la modificación', null=True, verbose_name='Estado nuevo (JSON)')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ejecutó la acción')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-fecha'],
                'managed': True,
            },
        ),
    ]
