# Generated by Django 4.2.8 on 2026-04-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_analisisvulnerabilidad_cursocapacitacion_ticket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroauditoria',
            options={'managed': False, 'ordering': ['-fecha'], 'verbose_name': 'Registro de auditoría', 'verbose_name_plural': 'Registros de auditoría'},
        ),
    ]
